spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: chaoxing
#      url: jdbc:mysql://120.131.6.144:3306/cultural_gallery?serverTimezone=UTC&characterEncoding=UTF-8
#      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/ovp?serverTimezone=GMT%2B8&characterEncoding=UTF-8
      url: jdbc:mysql://127.0.0.1:3306/osm?serverTimezone=GMT%2B8&characterEncoding=UTF-8


      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"





    dbcp2:
      initial-size: 20
      min-evictable-idle-time-millis: 3600000
      default-auto-commit: true
    tomcat:
      max-active: 50
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  servlet:
    context-path: /
#logging:
#  pattern:
#    console: "%d - %msg%n"
## path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
##  level:
#  level: debug

logging:
  file: catlina.log
  level: 
    level: debug
    package com.chaoxing.dao: info
#原数据配置文件
mybatis:
  typeAliasesPackage: com.chaoxing.ovp.bean.po
  mapper-locations: classpath:mappers/*.xml
# 开启接口文档.生产关掉
swagger:
  enable: true



file:
  localDir:  D:/chaoxing/file/static
#  localDir:  E:/ideaProject/ovp/static
  #file.localDir = /mnt
  # 文件映射的路径
fore:
  path: /static


#后台应用
unit:
  apps: {activity:"活动";live:"直播";test:"考试";vote:"投票"}

# 微信页面
wechat:
  APPID: wx20a0c40d12355808
  APPSECRET: 10ffd190c2125169366f0ed1e743583f

# 直播  anchorId是用户的uid
live:
  anchorId: 27304473
  sourceKey: 27304473
  source: 40
  schoolId: 3056

